version: "2.4"

services:
  rtsp-client:
    image: rtsp-client
    build: .
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      CAMERA_URL: $CAMERA_URL
    devices:
      - '/dev/dri'
      - '/dev/snd'
      - '/dev/video0'
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
